import './globals.css';
import { Inter } from 'next/font/google';
import { UserProvider } from './UserContext';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Register User',
  description: 'Generated by Camilo Bau',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
